### ISSUE TITLE
Would you please kindly upload the compliled Windows executable to your repo?

### ISSUE THREAD

**Issue by HuangShumin** [mbuilov/awk-windows#1]
Thank you in advance.

**Comment by mbuilov** [comment]
Hello.

No problem, I just pushed my current version of gawk.
It's work-in-progress, but it passes almost all tests.

You can download gawk.exe by the following link:

https://github.com/mbuilov/gawk-windows/blob/master/gawk.exe


Thank you for using GNU Awk!



Regards,
Michael.

**Comment by HuangShumin** [comment]
Much appreciated for your work!
